import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';

const PolicyLayout = ({ title, children }) => (
  <div className="max-w-4xl mx-auto mb-12">
    <div className="mb-6">
      <Link to="/" className="inline-flex items-center gap-2 px-4 py-2 bg-white hover:bg-gray-50 border border-gray-200 text-text-main text-sm font-medium rounded-lg transition-colors shadow-sm">
        <ArrowLeft size={16} /> Back to Home
      </Link>
    </div>
    <div className="corporate-card p-8 md:p-12">
      <h1 className="text-3xl font-bold mb-8 text-text-main border-b border-gray-100 pb-6">{title}</h1>
      <div className="prose prose-blue max-w-none text-text-muted space-y-6 leading-relaxed">
        {children}
      </div>
    </div>
  </div>
);

const CompanyDetails = () => (
  <div className="mt-12 p-6 bg-background rounded-xl border border-gray-200">
    <h3 className="text-lg font-bold text-text-main mb-4">Company Details</h3>
    <ul className="space-y-2 text-sm">
      <li><strong className="text-text-main">Domain Name (Website):</strong> www.prolync.in</li>
      <li><strong className="text-text-main">Company Name (Platform Owner):</strong> Prolync Student Workspace</li>
      <li><strong className="text-text-main">Registered Office Address:</strong> XYZ Building, Tech Park</li>
      <li><strong className="text-text-main">City & State (Jurisdiction):</strong> Chennai, TamilNadu</li>
    </ul>
  </div>
);

export const Terms = () => (
  <PolicyLayout title="Terms & Conditions">
    <p>This document is an electronic record in terms of the Information Technology Act, 2000 and rules thereunder as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>
    <p>This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries Guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of the domain name, including the related mobile site and mobile application (hereinafter referred to as the “Platform”).</p>
    <p>The Platform is owned and operated by the Platform Owner (details provided at the end of this document).</p>
    <h3 className="text-text-main text-xl font-bold mt-6">Key Terms</h3>
    <ul className="list-disc pl-5 space-y-2">
      <li><strong>1. Eligibility & Registration:</strong> To access and use the Services, you agree to provide true, accurate, and complete information.</li>
      <li><strong>2. Accuracy of Information:</strong> Neither we nor any third parties provide any warranty or guarantee as to the accuracy.</li>
      <li><strong>3. Use of Services:</strong> Your use of our Services and Platform is solely at your own risk.</li>
      <li><strong>4. Intellectual Property:</strong> The contents of the Platform are proprietary.</li>
      <li><strong>5. Prohibited Use:</strong> You agree not to use the Platform or Services for unlawful purposes.</li>
    </ul>
    <CompanyDetails />
  </PolicyLayout>
);

export const Privacy = () => (
  <PolicyLayout title="Privacy Policy">
    <p>Your privacy is very important to us. This Privacy Policy explains how we collect, use, and protect your personal information when you shop with us.</p>
    <h3 className="text-text-main text-xl font-bold mt-6">1. Information We Collect</h3>
    <p>When you place an order or interact with our website, we may collect:</p>
    <ul className="list-disc pl-5">
      <li>Your name, Phone number, Email address</li>
      <li>Shipping and billing address</li>
      <li>Payment details (processed securely via third-party gateways)</li>
    </ul>
    <h3 className="text-text-main text-xl font-bold mt-6">2. How We Use Your Information</h3>
    <p>We use your information to process orders, provide customer support, and improve our website services.</p>
    <h3 className="text-text-main text-xl font-bold mt-6">3. Sharing Your Information</h3>
    <p>We do not sell or rent your personal information to third parties. We only share it with trusted service providers to fulfill your order.</p>
    <CompanyDetails />
  </PolicyLayout>
);

export const Refund = () => (
  <PolicyLayout title="Refund Policy">
    <p>We offer a 7-day return/refund window, which means you can request a return within 7 days of receiving your item or service access.</p>
    <h3 className="text-text-main text-xl font-bold mt-6">Refund Process</h3>
    <p>After we receive and inspect your return request, we’ll notify you via email regarding the status of your refund.</p>
    <ul className="list-disc pl-5">
      <li>If approved, your refund will be credited automatically to your original method of payment within 10 business days.</li>
      <li>Shipping charges (if any) are non-refundable unless the return is due to our error.</li>
    </ul>
    <CompanyDetails />
  </PolicyLayout>
);

export const Shipping = () => (
  <PolicyLayout title="Shipping & Replacement Policy">
    <p>We aim to dispatch all orders promptly and deliver them within the estimated time frame. Orders are typically delivered within 10 to 15 business days.</p>
    <h3 className="text-text-main text-xl font-bold mt-6">Replacements</h3>
    <p>If you receive a damaged or defective item, please report it to us within 48 hours of delivery along with photos/videos as proof. Replacements are subject to stock availability.</p>
    <CompanyDetails />
  </PolicyLayout>
);

export const Contact = () => (
  <PolicyLayout title="Contact Us">
    <p>If you have any questions, concerns, or need support with your Prolync student workspace, please feel free to reach out to us through the details below.</p>
    <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mt-8">
      <div className="bg-background border border-gray-200 p-6 rounded-xl flex items-center gap-4">
        <div className="w-12 h-12 rounded-full bg-blue-50 flex items-center justify-center text-primary text-xl">📞</div>
        <div>
          <h4 className="text-text-main font-semibold">Phone</h4>
          <p className="text-text-muted">+91 6385499454</p>
        </div>
      </div>
      <div className="bg-background border border-gray-200 p-6 rounded-xl flex items-center gap-4">
        <div className="w-12 h-12 rounded-full bg-blue-50 flex items-center justify-center text-primary text-xl">✉️</div>
        <div>
          <h4 className="text-text-main font-semibold">Email</h4>
          <p className="text-text-muted">contact@prolync.in</p>
        </div>
      </div>
    </div>
    <CompanyDetails />
  </PolicyLayout>
);
